dateModified: 1622537053
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: 'The Rarities'
  replyToEmail: null
  template: ''
  transportSettings:
    password: $SYSTEM_EMAIL_PASSWORD
    timeout: '10'
    username: $SYSTEM_EMAIL_ADDRESS
  transportType: craft\mail\transportadapters\Gmail
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'The Rarities'
      prependSubject: ''
      successFlashMessage: 'Your message has been sent.'
      toEmail: $SYSTEM_EMAIL_ADDRESS
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: '@assetBaseUrl/static/admin/css/app.css'
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: OT08DXXOGO6FBJIS4OUSZY58
    schemaVersion: 1.0.0
  linkit:
    edition: standard
    enabled: true
    licenseKey: ZZJMLIJ06W3QPSLLGZB26EZA
    schemaVersion: 1.0.8
  navigation:
    edition: standard
    enabled: true
    licenseKey: QB4L2S36UFSSG4H8W5GGEYJS
    schemaVersion: 1.0.21
  neo:
    edition: standard
    enabled: true
    licenseKey: 6P7MMNSL34TCPE5353DC5IKU
    schemaVersion: 2.8.16
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 0FIOZ9PM9NKSYJ35D4YLZ3QG
    schemaVersion: 3.0.9
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '🚧⚙ '
      devModeTitlePrefix: '🚧 '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
system:
  edition: pro
  live: true
  name: 'The Rarities'
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
