fieldLayouts:
  cdd6206e-8f43-4c0a-b19c-db255bf8d727:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b4704f34-c3e9-4bdf-8ff3-b4eb73cdcce1 # Excerpt
            instructions: ''
            label: Subtitle
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: Image
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 47eaa35e-391f-4599-b181-0dfdafa85779 # Hero Image
            instructions: ''
            label: Image
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: Copy
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: cc11f94c-8711-44bd-8585-51503c7356d4 # Title
            instructions: ''
            label: 'Eyebrow Title'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66116a0a-e8a8-455a-af9d-4035d4516014 # Subtitle
            instructions: ''
            label: 'Eyebrow Subtitle'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 52adb6fa-a30d-46da-93a0-9684815d778f # Entity Excerpt
            instructions: ''
            label: Excerpt
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4a186240-4cb8-4774-8782-4e0d96e7e0d2 # Page Modules
            instructions: ''
            label: Modules
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
handle: about
hasTitleField: true
name: About
section: 10470e89-d4a6-40ff-9e62-c4d3db762b1f # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
