fieldLayouts:
  d183b4ed-2aae-4878-90a8-cc8837717543:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 47eaa35e-391f-4599-b181-0dfdafa85779 # Hero Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4a186240-4cb8-4774-8782-4e0d96e7e0d2 # Page Modules
            instructions: ''
            label: Modules
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: b4704f34-c3e9-4bdf-8ff3-b4eb73cdcce1 # Excerpt
            instructions: ''
            label: Description
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5a3762c3-bdd5-4e14-9b14-254a7c6ee23e # Image Gallery
            instructions: 'Images display at 3:2 on desktop'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            style: tip
            tip: 'Content displays on product detail pages.'
            type: craft\fieldlayoutelements\Tip
        name: Summary
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e762d0f3-5afa-4d15-b44e-309f34f78fcd # Logo
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 72b78399-b055-4873-9eac-a1fe1dd4941c # Follow Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Attributes
        sortOrder: 3
handle: brand
hasTitleField: true
name: Brand
section: 38f82feb-a29d-41bf-99fd-e274400842e6 # Brands
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
