fieldLayouts:
  b72250f2-d2c6-40ec-a284-7bfed1f5b53a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 4f0f45ee-6285-497b-89e7-ca5659c26c2b # Body
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4704f34-c3e9-4bdf-8ff3-b4eb73cdcce1 # Excerpt
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 1318ea66-9a2e-4f4f-9ed9-8e74967b4a89 # Image
            instructions: ''
            label: 'Index Image'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 885715a3-eecb-4ec7-8531-5108e896fd52 # Experience Categories
            instructions: ''
            label: Categories
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dd9605f6-deef-4b1b-8dbc-cbd120db865d # Experience Category
            instructions: ''
            label: 'Primary Category'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Attributes
        sortOrder: 2
handle: experience
hasTitleField: true
name: Experience
section: 25aef36f-c397-4e41-a229-632bdc12bb3b # Experiences
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
