fieldLayouts:
  63ed6379-7de6-49f1-9d3f-9a852045cc9d:
    tabs:
      -
        elements:
          -
            heading: Copy
            type: craft\fieldlayoutelements\Heading
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b4704f34-c3e9-4bdf-8ff3-b4eb73cdcce1 # Excerpt
            instructions: ''
            label: Subtext
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: Image
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 47eaa35e-391f-4599-b181-0dfdafa85779 # Hero Image
            instructions: ''
            label: Image
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 46517e3e-9148-407e-ab0b-2e4dfb062a35 # Experiences
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Articles
        sortOrder: 2
handle: experienceIndex
hasTitleField: true
name: 'Experience Index'
section: 4f29a97d-d232-4e7f-99a8-85d7f30a420b # Experience Index
sortOrder: 1
titleFormat: Experiences
titleTranslationKeyFormat: null
titleTranslationMethod: site
