fieldLayouts:
  71230103-f94c-45b5-b28f-1d2297dcc68e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1318ea66-9a2e-4f4f-9ed9-8e74967b4a89 # Image
            instructions: ''
            label: 'Background Image'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: edc8fef3-07d2-4ce6-9a8c-34e2701ac3bd # Video
            instructions: ''
            label: 'Background Video'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: login
hasTitleField: false
name: Login
section: dc0a045f-66c5-46e6-9dd6-29ff00c42b84 # Login
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
