fieldLayouts:
  47b732aa-ddd2-4ef0-98f1-e03cf1751e7c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 263e1056-afb5-429d-b3b8-287f2a050408 # About
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6266cc6d-2bc8-451f-bc34-9087cc4b2eba # Price
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 15a62ab8-8d4a-4341-a852-4e77938dec79 # Size
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 128d077b-94b8-4567-9cc9-2e5af3177542 # Images
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: a19b4f4a-6010-48ed-9980-34edabe8002d # Tasting Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 60f74584-3fd1-4c57-bd83-56842dc4d2be # Pairings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 080d7b67-a050-4636-a1c3-54972a6819af # Aging
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Details
        sortOrder: 2
      -
        elements:
          -
            heading: Products
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 3cba8f71-c48d-44da-85ff-9a266453a160 # Related Title
            instructions: ''
            label: Title
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3fc9ec2b-e501-447a-981f-9669fc7ae901 # Products
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: Editorial
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 552fa9b3-fce0-4feb-8f32-91959ef60225 # Editorials
            instructions: ''
            label: Entries
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Related
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 647d9c0b-fbde-43b6-95e0-6a66eeb1a7f5 # Brand
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1318ea66-9a2e-4f4f-9ed9-8e74967b4a89 # Image
            instructions: ''
            label: 'Index Image'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4704f34-c3e9-4bdf-8ff3-b4eb73cdcce1 # Excerpt
            instructions: 'Displays when product is featured in a hero format. '
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Attributes
        sortOrder: 4
handle: product
hasTitleField: true
name: Product
section: b9e160d4-4128-47ad-863a-65d3309a9e14 # Products
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
