contentColumnType: string
fieldGroup: 2c323421-38b1-4c3a-a8de-f758dfba032f # Common
handle: animatedScenes
instructions: ''
name: 'Animated Scenes'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
