contentColumnType: string
fieldGroup: 2c323421-38b1-4c3a-a8de-f758dfba032f # Common
handle: normalWideSelect
instructions: ''
name: 'Normal / Wide - Select'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Normal
        -
          - value
          - normal
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
