contentColumnType: string
fieldGroup: 2c323421-38b1-4c3a-a8de-f758dfba032f # Common
handle: normalHeroSelect
instructions: ''
name: 'Normal / Hero - Select'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Normal
        -
          - value
          - normal
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Hero
        -
          - value
          - hero
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
