contentColumnType: string
fieldGroup: 2c323421-38b1-4c3a-a8de-f758dfba032f # Common
handle: subNavigationBlocks
instructions: ''
name: 'Sub Navigation Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_subnavigationblocks}}'
  maxBlocks: '3'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
