fieldLayouts:
  1a5e8e6b-708b-4f98-9598-fce846f3157b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: products
name: Products
siteSettings:
  3e2858d8-00c1-48d3-84dc-a1508ebb5603: # Rarities
    hasUrls: true
    template: products/index
    uriFormat: 'products/{slug}'
structure:
  maxLevels: null
  uid: 11f80e8a-9801-477d-87a0-54ce6a07756f
