description: ''
handle: privateClientManagers
name: 'Private Client Managers'
permissions:
  - accesssitewhensystemisoff
  - accesscpwhensystemisoff
  - accesscp
  - registerusers
  - moderateusers
  - assignuserpermissions
  - 'assignusergroup:5353754a-7fa0-42d4-a51a-befd6e2f70de' # Private Clients
  - assignusergroups
  - administrateusers
  - editusers
  - deleteusers
  - 'utility:queue-manager'
