fieldLayouts:
  07cf62d2-5c02-4f1c-84c4-927c59d315b0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: efd5463b-0d13-4a5b-9e63-a7553e5adaa4 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 137d4feb-8994-4ed2-8c8b-fa575599d9a4 # Attribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bde9e72f-0718-4522-99d5-f28abbb76ce7 # Object Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7ca6786-ae8e-41b6-973b-bf9eee901efd # Object Fit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0294fcc-b120-4295-b5cc-63d83edcbe1e # Background Blend
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cab002e8-876d-4245-ac1c-9eee4cc0f426 # Optimized Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: images
hasUrls: true
name: Images
settings:
  path: '@assetBasePath/uploads'
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: '@assetBaseUrl/uploads'
