childBlocks: null
field: 4a186240-4cb8-4774-8782-4e0d96e7e0d2 # Page Modules
fieldLayouts:
  0cb2289a-7734-4ada-97ad-c7741cc07a98:
    tabs:
      -
        elements:
          -
            fieldUid: cc11f94c-8711-44bd-8585-51503c7356d4 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66116a0a-e8a8-455a-af9d-4035d4516014 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3fc9ec2b-e501-447a-981f-9669fc7ae901 # Products
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 87e5adce-325b-4169-931f-3e097fd39c68 # Normal / Hero - Select
            instructions: ''
            label: 'Lead Format'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
handle: featuredProducts
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Featured Products'
sortOrder: 3
topLevel: true
