childBlocks: ''
field: 4a186240-4cb8-4774-8782-4e0d96e7e0d2 # Page Modules
fieldLayouts:
  e09a918d-6e8c-48b5-884f-3ce945db3420:
    tabs:
      -
        elements:
          -
            fieldUid: 1318ea66-9a2e-4f4f-9ed9-8e74967b4a89 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: media
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Media
sortOrder: 2
topLevel: true
