childBlocks: ''
field: 4a186240-4cb8-4774-8782-4e0d96e7e0d2 # Page Modules
fieldLayouts:
  17406d13-9397-4faf-8635-52185c898b61:
    tabs:
      -
        elements:
          -
            fieldUid: 1318ea66-9a2e-4f4f-9ed9-8e74967b4a89 # Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Media
        sortOrder: 1
      -
        elements:
          -
            fieldUid: cc11f94c-8711-44bd-8585-51503c7356d4 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66116a0a-e8a8-455a-af9d-4035d4516014 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f0f45ee-6285-497b-89e7-ca5659c26c2b # Body
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Text
        sortOrder: 2
      -
        elements:
          -
            heading: Layout
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: cc646fda-a838-4ede-ae03-065f3918d03c # Left / Right - Select
            instructions: 'On tablet +'
            label: 'Media Position'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 8b1f7546-41e6-4fcf-8e69-8956e0a26f2f # Normal / Wide - Select
            instructions: 'On tablet +'
            label: 'Media Size'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Settings
        sortOrder: 3
handle: mediaText
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Media + Text'
sortOrder: 2
topLevel: true
