childBlocks: null
field: 4a186240-4cb8-4774-8782-4e0d96e7e0d2 # Page Modules
fieldLayouts:
  919d7140-dcf3-492c-b844-4fdf1a389b4b:
    tabs:
      -
        elements:
          -
            fieldUid: f37621db-e2e0-4cde-beff-7687c349c859 # Quote
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 137d4feb-8994-4ed2-8c8b-fa575599d9a4 # Attribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: quote
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Quote
sortOrder: 4
topLevel: true
