childBlocks: ''
field: 4a186240-4cb8-4774-8782-4e0d96e7e0d2 # Page Modules
fieldLayouts:
  87397586-d8dd-4b34-b535-df7b4243d6b0:
    tabs:
      -
        elements:
          -
            fieldUid: 6a195cfb-9bdd-4b9c-9c29-f238997bff25 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f0f45ee-6285-497b-89e7-ca5659c26c2b # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Text
        sortOrder: 1
handle: text
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
