childBlocks: ''
field: b35c8f0f-938f-4a51-84fe-69672691817b # Animated Scenes
fieldLayouts:
  44f1d23a-7f9b-467c-be90-9a44a12b53b1:
    tabs:
      -
        elements:
          -
            fieldUid: cc11f94c-8711-44bd-8585-51503c7356d4 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f0f45ee-6285-497b-89e7-ca5659c26c2b # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: text
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
