tabs:
  -
    elements:
      -
        fieldUid: 3f7c64ea-5c54-49fa-9321-1ef66f2fe27b # Phone
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 25
    name: Contact
    sortOrder: 1
  -
    elements:
      -
        fieldUid: 7812ade1-d6d8-4576-9406-b0486a72e62e # Private Client Manager
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Manager
    sortOrder: 2
