tabs:
  -
    elements:
      -
        fieldUid: 99f92f86-a977-4d67-aefd-17c5a60d5e52 # Address
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        fieldUid: 3f7c64ea-5c54-49fa-9321-1ef66f2fe27b # Phone
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
    name: Contact
    sortOrder: 1
  -
    elements:
      -
        fieldUid: 7812ade1-d6d8-4576-9406-b0486a72e62e # Private Client Manager
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 50
      -
        template: admin/users/_cellar
        type: craft\fieldlayoutelements\Template
        width: 50
    name: Cellar
    sortOrder: 2
