tabs:
  -
    elements:
      -
        fieldUid: 7812ade1-d6d8-4576-9406-b0486a72e62e # Private Clients
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Clients
    sortOrder: 1
  -
    elements:
      -
        template: admin/users/_cart
        type: craft\fieldlayoutelements\Template
        width: 100
    name: Cart
    sortOrder: 2
