enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3e2858d8-00c1-48d3-84dc-a1508ebb5603: # Rarities
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
