field: baa73683-0ba8-4951-a09c-cc4eaa612369 # Rich Text Tabs
fieldLayouts:
  88b9a8fb-4c49-4622-a473-efb6a73c8c48:
    tabs:
      -
        elements:
          -
            fieldUid: c5b259b1-b17e-4b3d-b363-f9f72447e98b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 79008308-10d9-4aed-8f57-0ebf884c485a # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  79008308-10d9-4aed-8f57-0ebf884c485a: # Body
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c5b259b1-b17e-4b3d-b363-f9f72447e98b: # Title
    contentColumnType: text
    fieldGroup: null
    handle: tabTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: tab
name: Tab
sortOrder: 1
